### ISSUE TITLE
Los archivos de prueba para el Ejercicio 2 del Taller 4 no se encuentran disponibles

### ISSUE THREAD

**Issue by marcio-pg** [milogz/HCAD#2]
`
En la siguiente celda encuentras declarada una variable que almacena una cadena de caracteres representativa de la ruta relativa para el archivo "tesoro.txt". Recuerda que para los talleres, los archivos necesarios están en el subdirectorio "Archivos".`

En la prueba se utilizan 2 archivos: 

`
directorio = "./Archivos/tesoro.txt"
directorio_prueba = "./Archivos/tesoro_2.txt"`

Sin embargo estos parecen no encontrarse disponibles en el repositorio.

**Comment by terrok9** [comment]
Push commited hace 25 días con el problema solucionado.
